spring:
  application:
    name: chagok

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?rewriteBatchedInserts=true
    hikari:
      password: chagok
      username: chagok

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      hibernate.jdbc.batch_size: 50

  batch:
    job:
      enabled: false  # 자동 실행 끄기
  data:
    redis:
      repositories:
        enabled: false

# DB 날린 경우 (혹은 배치 처음 실행할 경우) 주석 해제
#    jdbc:
#      initialize-schema: always

server:
  port: 8080
  servlet:
    session:
      timeout: 30m

app:
  frontend-base-url: http://localhost:5173
